### ISSUE TITLE
ENH enable cosmosis restarting

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/firecrown#109]
Notes from @joezuntz 

> I haven't documented it as it's only in the develop/standalone branches, but you just set the parameter ('runtime', 'resume') = 'True' and it will do the rest, as long as the output file name is the same. So should be able to just use the same analysis id and it will work.

We will also need to add a `--resume` parameter to the run-cosmosis function which takes in the path to the `output_*` dir to resume from.

**Comment by vitenti** [comment]
Obsolete, Firecrown no longer calls CosmoSIS. Users can directly use CosmoSIS (and Cobaya and NumCosmo) ability to resume chains.
