### ISSUE TITLE
Fourier-space testing

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/firecrown#113]
After talking to @chihway , it seems it'd be useful to check firecrown can analyze fourier-space data successfully. To that end we'd need:

1. A fake data vector consisting of a set of 3x2pt power spectra from CCL (with its covariance, which can be Gaussian in fsky approximation).
2. A firecrown input file that is able to analyze that data.
3. To run firecrown and show that we can recover the input cosmology.

Pinging possible heroes: @humnaawan

**Comment by damonge** [comment]
quick question for @chihway 
It'd be good to gauge the level of realism we should aim to here so, in the real-space case, how did you deal with:
- theta-bin window functions
- noisy data (i.e. did your input data have noise in it or was it a pure CCL prediction?)

**Comment by chihway** [comment]
We actually didn't do this exact test, we went straight to cosmoDC2 measurements (would probably still be good to do this though). So the window function is naturally included (though I'm not actually now sure how CCL is modeling it), and there is the noise Joe has added.

I suggest you start with a noiseless DV just to get firecrown set up, and we can switch out to either noisy DV or cosmoDC2 later.

**Comment by vitenti** [comment]
The functionality necessary to perform this kind of testing is being developed into Augur https://github.com/LSSTDESC/augur .

**Comment by tilmantroester** [comment]
Firecrown should have its own test suite that ensures it does what it claims to do. Outsourcing that to another package seems like a bad idea.

**Comment by vitenti** [comment]
We agree that there should be more tests in Firecrown to verify that the various parts do what they intend. That is why we are working on improving the design of many parts, to make them testable. We want to have unit tests for components, and for those tests to have high code coverage; we are far from that now.

We also need integration and physics validation tests. These are distinct from the unit tests, and are harder to specify. We want to be careful that such tests do not duplicate functionality that appears in other packages (such as Augur). That is why we had mentioned Augur above.
