### ISSUE TITLE
Incorporating CMB lensing into firecrown to do 5x2

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/firecrown#120]
In corporate a new source and the relevant APIs in order to do a 5x2 analysis with cosmoDC2.

**Comment by zhzhuoqi** [comment]
Some updates: 

firecrown now is able to read and store CMB lensing source, and to calculate 2-point statistics of galaxy weak lensing x CMB lensing (GK) and galaxy count x CMB lensing (NK). So now it can also run MCMC chains on NK and GK. 

Here are some test results of firecrown MCMC chains on NK and GK. The blue contours are constraints from firecrown, and the red contours, serving as the "benchmark", are constraints from some external MCMC pipelines. The two results seem to agree well with each other. 
![NK](https://user-images.githubusercontent.com/60624040/89060766-22c34880-d396-11ea-8d43-b1c33ea84a01.png)

![GK](https://user-images.githubusercontent.com/60624040/89060756-2060ee80-d396-11ea-92ad-4f006b9dd22f.png)
The details of these tests (with the config files) will be up in the firecrown/example folder soon.
