### ISSUE TITLE
Clarification of design of Mapping

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/firecrown#143]
The intended "lifecycle" of a  [`Mapping`](https://github.com/LSSTDESC/firecrown/blob/3d9dd5b47dd9853449c9f97cce3cbf7d727606a0/firecrown/connector/mapping.py)
object is:

1. Creation at MCMC framework configuration time. Currently, the `Mapping` object has no instance data that requires initialization at this time, but we are retaining this part of the lifecycle to provide the flexibility to add such state if it becomes needed. At this time, there is no need for an `__init__` function either in the `Mapping` class or its subclasses.
2. Setting the state for the cosmology of the current MCMC sample. The method that does this is currently called `set_params`, but `set_cosmology` is probably a better name. This method should be marked `final` because we do not want derived classes to alter the set of parameters (instance data) that are carried by the class. Subclasses are intended to alter the way the parameters are calculated. 

The class `Mapping` uses descriptors to make sure that the setting of instance data retains the correct type for the data. But the current implementation does not prevent the addition of unexpected instance data into a `Mapping` object. Such an insertion would avoid the protection given by the descriptors. By using `__slots__` to contain the instance data, insertion of unexpected instance data would be prevented.

**Comment by vitenti** [comment]
Since this is not a user visible class we decided that this is not necessary.
