### ISSUE TITLE
Support modular likelihood files

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/firecrown#145]
Right now, importing modules that reside in the same directory as the module that provides `likelihood` does not work out of the box.
The specific use case I have in mind is a module `likelihood_utils.py` that includes functions to build up the sources and stats dicts and a set of lean likelihood modules `3x2pt.py`, `shear_only.py`, etc, that import these functions from `likelihood_utils.py`.

A simple `import likelihood_utils` does not work, presumably because the working directory is somewhere else during the cosmosis execution.
I'm currently using a workaround along the lines of
```
import sys
import os
sys.path.append(os.path.split(__file__)[0])
import likelihood_utils
```
A cleaner solution would be appreciated, however.

**Comment by vitenti** [comment]
Hello @tilmantroester do you have a working example of this use?

**Comment by tilmantroester** [comment]
See for example https://github.com/LSSTDESC/star-challenge/blob/inference/firecrown-parameter-inference/likelihood/star_3x2pt.py

**Comment by vitenti** [comment]
Your code is actually the beginning of the movement towards likelihood building centered around the SACC file. We were already planning that. I'll try to find a better solution for your current problem but in a near future we will probably migrate your code to inside Firecrown. What do you think?

**Comment by tilmantroester** [comment]
Sounds good to me.
