### ISSUE TITLE
Parametrized Likelihoods

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/firecrown#202]
We have been discussing ways to make firecrown likelihoods parametrizable - i.e. passing options into them to tweak their behaviour. The most immediate use case is selecting which SACC file to pass into the likelihood instead of hard-coding it.

@marcpaterno mentioned that there is a plan  to change the firecrown likelihood python files so that instead of instantiating a likelihood directly they provide a function that returns one. That function could then straightforwardly take options from the configuration.

I think there's then a few questions to consider:
- Do we allow the current behaviour where the `likelihood` is instantiated directly?  It's easy to check whether the object in the module is a function or a likelihood instance, so I don't think it's technically challenging. It might be confusing to have the two choices though.
- How do we pass options in - should we try to warn about unsued options in some way?  This could be left up to the likelihood designer, if options are passed in by keyword - since they could either specify keywords or use `**kwargs`.

Anything else to consider?

**Comment by marcpaterno** [comment]
I'm interested in hearing if anyone thinks it is important to keep the current behavior.

My current preference would be to support only the proposed new behavior. I believe that it would be confusing to have the two methods, and it would also be an increased maintenance burden. 

Part of the implementation of this would be to translate all the examples in Firecrown to use that new behavior. I'd be happy to help others translate their own likelihood scripts to the newer form.

**Comment by am610** [comment]
Strongly voting, for the motion.

**Comment by joezuntz** [comment]
I think Ayan was talking about the overall motion above. 

On the specific thing about whether it's worth keeping the old behaviour, I think now is the right time to break backwards compatibility, before heavy use gets started. So I think fine to drop the old behaviour.

**Comment by am610** [comment]
Yes, the overall motion of updating the framework.

**Comment by tilmantroester** [comment]
I see the use case for passing options to the likelihood from the sampling frameworks for quick prototyping. On the other hand, off loading these options to the sampler introduces the risk of inconsistencies, depending on how the likelihood is run. What I like about the current setup is that I can drop the same likelihood `.py` file into cosmosis or cobaya or run it directly and it behaves the same in all cases.
If likelihood options are supported, there should be functionality to automatically log the options somehow at runtime, as well as warnings when they're not being set.

I'd also like to retain the ability to create bespoke likelihoods with the current low-level interface. A high-level interface is useful for general users and production runs but for development a low-level interface is more useful.

**Comment by joezuntz** [comment]
What you're calling inconsistencies is exactly the same behaviour as what we're calling customization.

I definitely agree on logging - cosmosis will do this automatically in the header of the output file. Not sure about cobaya.

**Comment by am610** [comment]
> I see the use case for passing options to the likelihood from the sampling frameworks for quick prototyping. On the other hand, off loading these options to the sampler introduces the risk of inconsistencies, depending on how the likelihood is run. What I like about the current setup is that I can drop the same likelihood `.py` file into cosmosis or cobaya or run it directly and it behaves the same in all cases. If likelihood options are supported, there should be functionality to automatically log the options somehow at runtime, as well as warnings when they're not being set.
> 
> I'd also like to retain the ability to create bespoke likelihoods with the current low-level interface. A high-level interface is useful for general users and production runs but for development a low-level interface is more useful.

Since we are working on integrating Firecrown into the Time Domain pipeline at the moment, this function is mandatory at the moment for us.

**Comment by marcpaterno** [comment]
We have two design ideas on which we would like feedback (i.e., which do you prefer?).
In both cases, we are describing the interface for the function the user is to write.
This function will be called by Firecrown and should return a likelihood object.
The difference is what arguments are to be passed to the function.

1. a dictionary of configuration parameter names (strings) to values (strings, numbers, NumPy arrays of numbers)

2. a dictionary mapping strings to values, where the values are strings, numbers, np.arrays, lists, and dictionaries.
   The lists and dictionaries are also composed for strings, numbers, np.arrays, lists, and dictionaries. recursively.
   This is what is returned by `yaml.load`, when a user-defined class is *not* specified.
   
If we use design 1, the CosmoSIS pipeline ini file would contain a section for the likelihood module; the dictionary passed would be the contents of this section of the pipeline ini file. In Cobaya, the dictionary passed would be the contents of the appropriate section of the configuration YAML file. That YAML file will be required to contain only a "single level" of parameters. Firecrown would ensure that the Cobaya configuration provided conforms to this limitation.

In design 2, the CosmoSIS pipeline ini file would specify the name of a YAML file that Firecrown would load. The Cobaya configuration could be either section of the full YAML file, or the name of a YAML file to be loaded.

Both sampling frameworks already handle writing the configuration of all modules to the output of the sampling framework, so the user of either will have the configuration available with the output of the sampling process. Note that if we're using an external file (design 2), it is only the name of the file that is written to this output. If we use design 1, the output will contain the actual configuration parameters.

In both cases, one can always create a non-configurable likelihood by ignoring the argument passed to the "factory function".

@tilmantroester @joezuntz @am610 , please comment. Everyone else is also welcome to comment!

**Comment by joezuntz** [comment]
If we do option 1 for now then that's easily changeable to option two later, whereas the reverse isn't true. So I'd suggest doing that first and then seeing if it's too limiting.

**Comment by tilmantroester** [comment]
I second Joe's comment. Another point is that once you're in a regime where you have to carry around extra yaml files, that seems to defeat the point of the proposed functionality, since you might as well set the options in the .py likelihood specifications directly.

**Comment by vitenti** [comment]
Those are good points. I'll begin the implementation of option 1 and open a PR.
