### ISSUE TITLE
Document the agree-upon release policy

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/firecrown#227]
The release policy discussed and agreed upon at the recent MCP meeting should be written up.

**Comment by tilmantroester** [comment]
I think we should discuss if we want to restrict the requirement of backwards compatibility to a subset of the API. I could imagine that the API for top-level interactions (such as the creation and evaluation of likelihoods, statistics, and sources) remains stable but there are less guarantees for low-level functionality (for example, tracer objects).

**Comment by marcpaterno** [comment]
We agree with this idea. However, we think the code is not yet stable enough to clearly distinguish between the "external" and "internal" components. We propose to take this up again when the code has reached appropriate stability.
