### ISSUE TITLE
Unit test for firecrown/models/ ClusterMassRich.gen_bins_by_array

### ISSUE THREAD

**Issue by MoonzarinReza** [LSSTDESC/firecrown#300]
Issue: Create a unit test to test the functionality of ClusterMassRich.gen_bins_by_array. This function returns a list of paired bins  of richness from an input array of bins.

Possible solution: Adding a unit test in Firecrown/tests, to test whether the lower and the upper values of the returned richness bins match with the ones from the input array.

**Comment by marcpaterno** [comment]
Please check the head of the `master` branch, and tell us if the newly-added testing is sufficient.
