### ISSUE TITLE
Sample over logA_s in firecrown

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/firecrown#331]
Is it possible to sample over logA_s in firecrown. We discussed this before and there seems to be some workaround using cosmosis, but I'm not sure about cobaya. Could this be documented somewhere in the repo? Maybe in one of the examples?

**Comment by marcpaterno** [comment]
The firecrown code does not configure any of the samplers; it is the configuration of the sampler that configures the Firecrown code that the sampler calls.

For CosmoSIS, if what you want to obtain samples from a prior that is flat in `logA_s`, I think you can achieve this by using an exponential prior in `A_s`. The documentation for setting non-flat priors in CosmoSIS is at https://cosmosis.readthedocs.io/en/latest/usage/parameter_files/priors_ini.html?highlight=prior.

@joezuntz , please correct anything that I have gotten wrong here, and also please let us know where in the CosmoSIS documentation we should point for any additional information about configuring priors in CosmoSIS.

**Comment by marcpaterno** [comment]
Is there documentation for this somewhere on the CosmoSIS readthedocs site? I do not see `log1e10As` mentioned in the documentation for the consistency module at https://cosmosis.readthedocs.io/en/latest/reference/standard_library/consistency.html?highlight=consistency. Am I looking at the wrong place?
