### ISSUE TITLE
Integrate x-cut/k-cut cosmic shear 

### ISSUE THREAD

**Issue by pltaylor16** [LSSTDESC/firecrown#350]
We are trying to implement x-cut/k-cut cosmic shear (see e.g. https://arxiv.org/abs/2007.00675) as part of the desc-baryon-challenge. A public version of the code which computes the transformation matrix is available here: https://github.com/pltaylor16/x-cut .

**Comment by vitenti** [comment]
Hi @pltaylor16, do you need guidance on how to incorporate this transformation on C_ells produced by Firecrown? Or are you already creating a PR with this aim?

**Comment by pltaylor16** [comment]
Thanks for the reply @vitenti. Looking for a little guidance on the best way to go about doing this.
Ideally this could be merged into the main branch of Firecrown. 

To give you a little more background, the transformation assumes a fiducial cosmology which is fixed throughout inference. The transformation is then applied to the theory vector, data vector and covariance in a consistent way. One then can choose a new set of angular scale cuts on the transformed data vectors.

**Comment by vitenti** [comment]
Hello @pltaylor16 great, I'll turn this issue into a discussion and once we have a good plan we move to an issue or PR.
