### ISSUE TITLE
Systematics ordering

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/firecrown#43]
From a chat between @elikrause and @joezuntz :

Currently systematics can be run in an order which is scientifically inconsistent, like if a photo-z sys is applied after an IA or galaxy bias swhich uses that redshift.  We need a check to raise an error in this specific case.  

In future systematics may get more complicated, so we should watch this area carefully in case something more robust is needed in future.

Also - the nz_ vs _nz is way, way, way too confusing for someone browsing the code.  This needs to change to something more clear.

**Comment by jablazek** [comment]
[I'm starting this comment now. Will add more details and some pseudo code later.]

@joezuntz can you provide an example for the photo-z and IA or bias sys where ordering matters?

Here is another example which was a fiducial case informing the earlier TJPCosmo framework. Some IA models depend on the galaxy bias when determining the IA power spectra. Right now, this is just a question of linear galaxy bias, but could potentially be more complex in the future. Schematically:
for IA params (C1,C2)
linear bias model (b1) OR quadratic bias model (b1, b2)

P_IA = C1*P_ta(k) + C2*P_ tt(k)+b1*C1*P_dw(k)

In some cases (like the toy model above), it might not matter whether the bias model params or the IA model params are added first, as long as all of the necessary info is passed to CCL/FAST-PT to do the calculations. There would just need to be a check at the end to make sure that all of the necessary info for each systematic has been added by the other systematics. In the case above, the check would require both that a galaxy bias was applied to the source tracer AND that it was of the right format (e.g. linear or quadratic bias but not some other scale-dependent b(k))

There could also be a case where some more complex calculation needs to be done in Firecrown before passing to CCL, in which case the bias systematic would need to be applied before the IA systematic is applied. @elikrause , do you remember whether in the original TJPCosmo formulation the order mattered for nonlinear IA?

**Comment by beckermr** [comment]
I think changing the name `_nz` to something else is straight forward since those are private things and implementation details.

**Comment by vitenti** [comment]
Systematics now are always called in the order they were specified.
