### ISSUE TITLE
Typo in the inferred_galaxy_zdist file

### ISSUE THREAD

**Issue by AmandaFdSantos** [LSSTDESC/firecrown#452]
There is a typo in the `firecrown/firecrown/generators/inferred_galaxy_zdist.py` file, under the 'ZDistLSSTSRDBinCollection' class, in line 398. The name of the constant 'LSSST_Y10_SOURCE_BIN_COLLECTION' should be 'LSST_Y10_SOURCE_BIN_COLLECTION'.

**Comment by marcpaterno** [comment]
This is fixed by PR #453
