### ISSUE TITLE
Default values for SRD lens and sources distribution.

### ISSUE THREAD

**Issue by VGozzi** [LSSTDESC/firecrown#454]
It appears that LSST_Y1_SOURCE_BIN_COLLECTION and LSST_Y1_LENS_BIN_COLLECTION are utilizing the same values for alpha, beta, and z0 when generating the SRD distributions. Is this behavior intentional?  Furthermore, I have observed a discrepancy between the source SRD binned distributions in Firecrown Default and the CCLX examples.

**Comment by vitenti** [comment]
@VGozzi , we implemented proper bins for sources, please take a look at #463 , it will be merged soon.
