### ISSUE TITLE
Typo on SRD N(z) generator

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/firecrown#455]
Hi @vitenti and @marcpaterno !

I noticed there's a typo on one of the generators for the SRD N(z), `firecrown.generators.inferred_galaxy_zdist` has:
- `LSSST_Y10_SOURCE_BIN_COLLECTION`
- `LSST_Y10_LENS_BIN_COLLECTION`
- `LSST_Y1_LENS_BIN_COLLECTION`
- `LSST_Y1_SOURCE_BIN_COLLECTION`

Note that the first, the Y10 Source Bin Collection has an extra `s` in LSST.

**Comment by marcpaterno** [comment]
Hi Arthur,

Thanks for notifying us. We have already received a bug report, and this now fixed at the head of the master branch in the repository.

Best regards
M arc

From: Arthur Loureiro ***@***.***>
Date: Friday, September 20, 2024 at 7:44 AM
To: LSSTDESC/firecrown ***@***.***>
Cc: Marc F Paterno ***@***.***>, Mention ***@***.***>
Subject: [LSSTDESC/firecrown] Typo on SRD N(z) generator (Issue #455)

[EXTERNAL] – This message is from an external sender

Hi @vitenti<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vitenti&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=d3p0PLQb2ItFxNVHOOIv2tbqRE3Vbq3EtoL-OopFQXc&m=yo3A9lkRvZ7SDx_sjrI8vkuUQa60f_BsrDeVrGfDHKI95nPiwwedclAzouqb7pkV&s=nyL8fix2dXJXMmXXWBiU0vd3busn84TaTrb0naSlVGo&e=> and @marcpaterno<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_marcpaterno&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=d3p0PLQb2ItFxNVHOOIv2tbqRE3Vbq3EtoL-OopFQXc&m=yo3A9lkRvZ7SDx_sjrI8vkuUQa60f_BsrDeVrGfDHKI95nPiwwedclAzouqb7pkV&s=7XNWk6DbVaejeC60HT5ZX5IJd3wDyuuD7Pg7HuutHfo&e=> !

I noticed there's a typo on one of the generators for the SRD N(z), firecrown.generators.inferred_galaxy_zdist has:

  *   LSSST_Y10_SOURCE_BIN_COLLECTION
  *   LSST_Y10_LENS_BIN_COLLECTION
  *   LSST_Y1_LENS_BIN_COLLECTION
  *   LSST_Y1_SOURCE_BIN_COLLECTION

Note that the first, the Y10 Source Bin Collection has an extra s in LSST.
