### ISSUE TITLE
Sky systematics models

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/firecrown#46]
Eventually we will want to deal with sky and image level systematics that propagate into our summary statistics.  These may end up being dealt with at earlier stages, but not necessarily.

Most of these will presumably end up as multiplicative or additive systematics in some way.

- blending
- sensor systematics
- PSF-related systematics
- others

**Comment by vitenti** [comment]
This is now spread among several other projects and will be included into Firecrown as they are delivered. We should create an issue for each effect as they appear in each likelihood.
