### ISSUE TITLE
Cosmic shear example broken

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/firecrown#69]
I got this error when running the cosmic shear example:
`File "/Users/elisa/Documents/lsst_tjpcosmo/TJPCosmo/firecrown/ccl/statistics/two_point.py", line 22, in _cached_angular_cl
    l_logstep=1.15, l_linstep=6e4)
TypeError: angular_cl() got an unexpected keyword argument 'l_logstep'`
Looks like an incompatibility with CCL v2.

**Comment by beckermr** [comment]
Yup this is on my todo list to upgrade to v2.
