### ISSUE TITLE
Implement Cluster likelihood

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/firecrown#81]
The way this should be done is as follows:
* Cluster likelihood will be composed of power spectra in auto and cross in bins of richness or some other tracer of cluster mass. sacc can do this. Additionaly, we need number counts for the same richness bins -- sacc should be extended to deal with this. 
 * The rest is very similar to 3x2pt -- the correlation part should flow through the same code. The number counts should be implemented separately, but we have the code.

Some care needs to be taken re covariances... Let's have a first pass assuming independence and then work out what is the most natural way to implement covariances.

I'm assigning this to Eduardo Rozo, who should at least know to whom to offload this. @erozo

**Comment by beckermr** [comment]
@elikrause is already on this - see the open PRs

**Comment by elikrause** [comment]
See #desc-cl-tjp slack channel for discussions on the fireCrown part of this.
Can someone else comment on the status of counts (as a function of mass proxy) in SACC? There was a start on this during the Edinburgh sprint meeting.

**Comment by slosar** [comment]
Some work has already started on this and there is a pull request: https://github.com/LSSTDESC/firecrown/pull/62

However, I do not think it is finished and so I will leave this ticket open for now (but feel free to close it)

**Comment by vitenti** [comment]
Done in PR #204
