### ISSUE TITLE
Module to (optionally) maximize likelihood and calculate 2nd derivative matrix

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/firecrown#82]
Occasionally you want to do quite estimation of likelihood shifts under different assumption with a rough estimate of errors. In this case all you need to do is to maximize likelihood and calculate 2nd der matrix. This will also allow a Fisher-matrix like calculationa and perhaps even acta as a tool to estimate proposal matrix for MCMC.

**Comment by beckermr** [comment]
Does cosmosis do this @joezuntz?

**Comment by joezuntz** [comment]
yes, with a suitable choice of options.  When I craft the examples (#76) I'll include one of these.

**Comment by beckermr** [comment]
Great! I'm going to close this issue for now then.
