### ISSUE TITLE
Complete IA and baryon modelling 

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/firecrown#83]
There is some IA modelling in firecrown, e.g. `LinearAlignmentSystematic`. But we likely need multiple IA models and also some sort of marginalisation over baryons. The modelling should be at the minimum level we think we need for LSST Y1 data analysis and/or SRD forecasting.

Assigning to Eliza, we also want chihway chang and mustapha to be on board as WL conveners.

**Comment by elisachisari** [comment]
New developments in CCL by @jablazek and @damonge, soon to be merged, should enable a bit more flexibility for IA.
We similarly have some baseline baryons model.
We don't know for sure that either of these will be enough for Y1. I think we should use the SRD forecasting + DC2/3 to answer this question as a sort of iterative process. How much of a bias do we introduce in cosmological parameters by varying our assumptions about the true universe and the model we use?
