### ISSUE TITLE
Add PZ widths systematics model

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/firecrown#84]
At the moment there are only PZ shifts but no PZ widths in `firecrown/ccl/systematics/pz.py`. 
PZ widths seems like an easy thing to add. Long term we want a better way modelling PZ uncertainity, including potentially using samples of N(z) and/or eigen-vector like marginalization. 

Let's make PZ responsible so that they feel so bad about it that they will implement something better.

**Comment by slosar** [comment]
This is a very specific request, c.f. more general ticket: https://github.com/LSSTDESC/firecrown/issues/50

**Comment by rmandelb** [comment]
The long-term more general parametrization could be explored as part of https://confluence.slac.stanford.edu/display/LSSTDESC/Requirements+on+PZ+errors+for+3x2pt ?

**Comment by beckermr** [comment]
Yes! I was wondering if @empEvil was working on this...

**Comment by marcpaterno** [comment]
The current implementation has `PhotoZShift` in both `weak_lensing.py` and `number_counts.py`. These should be extracted and put into a single place where they can be used by both modules, perhaps into a more general `dn/dz` class to be used by both weak lensing and number counts.

Is anyone from the PZ working group interested in adding the width effects? Would the same proposed `dn/dz` have a way to introduce the width effects that would be useful to both weak lensing and number counts?

Adding @bruno-moraes to the discussion participants.

**Comment by tilmantroester** [comment]
Having a single `PhotoZ` systematic for both weak lensing and clustering would be useful I think. Adding width scaling on top of the existing shift systematic can be done quite easily.
There's also ongoing work on a more general framework to get n(z) uncertainties from RAIL into firecrown.
