### ISSUE TITLE
add systematics that effect more than one source

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/firecrown#85]

**Comment by beckermr** [comment]
@elikrause this would be between the source and statistics level - IDK if you have thoughts here

**Comment by elikrause** [comment]
@beckermr Can you expand a bit? Is this a systematic that affects multiple tomography/richness bins of the same source class (e.g., IA with power-law z dependence; MOR as a function of lambda and z), or a systematic affects different source classes  (e.g., WL and LSS)?
Is there a prescription for the effect on each source?

**Comment by beckermr** [comment]
Well, imagine we are doing the photo-z sampling thing from realizations. How does this fit into our current scheme?

**Comment by elikrause** [comment]
It seems to me that this would be a source systematic, as it effect on the statistics level is described by modifying the redshift attribute of each source.
If we have a module that draws correlated (between tomography bins, and different source types) photo-z realizations, the source systematic for source X would be a function that passes the subset of the realization containing the n(z) for source X into the redshift attribute of source X.
Does that make sense?

**Comment by beckermr** [comment]
Ahhhhhhh! Yes, I know how to do this now.

**Comment by beckermr** [comment]
This issue can be closed in favor of a specific issue for photozs
